schedules:
  - cron: "32 13 * * *"
    displayName: Regular check run
    branches:
      include:
        - master
    always: true

trigger:
  - master

pool:
  vmImage: 'ubuntu-latest'

steps:
  - task: NodeTool@0
    inputs:
      versionSpec: '12.x'
    displayName: 'Install Node.js'
  - task: Cache@2
    inputs:
      key: npm | $(Agent.OS) | package-lock.json
      path: /home/vsts/.npm
      restoreKeys: |
        npm | "$(Agent.OS)"
    displayName: Cache NPM Packages
  - script: npm ci
    displayName: 'npm install'
  - script: npm run cy:verify
    displayName: 'Cypress Verify'
  - script: |
      npx print-env AGENT
      npx print-env BUILD
      npx print-env SYSTEM
      npm run cy:regular
    condition: eq(variables['Build.Reason'], 'Schedule')
    displayName: 'Scheduled regular check tests'
    env:
      # avoid warnings about terminal
      TERM: xterm